### ISSUE TITLE
Update ITEMLISTIND_insertlines job

### ISSUE THREAD

**Issue by DustinSigwardNete** [NETESOLUTIONS/FOCUS-Maintenance#4]
The following fields need to be updated so they are no longer null.  Either in the insertlines job or as part of the main update job.
[ITEMLISTIND_insertlines Example.xlsx](https://github.com/NETESOLUTIONS/FOCUS-Maintenance/files/106135/ITEMLISTIND_insertlines.Example.xlsx)
![image](https://cloud.githubusercontent.com/assets/10310724/12605583/33352dca-c494-11e5-9548-77c4849bf015.png)

**Comment by gregmarlownete** [comment]
CTSAP all months has been updated.  Please ensure additional lines to ITEMList_individual have all the required information as they are entered.  Thanks
