### ISSUE TITLE
Update budgeted values for all vendors

### ISSUE THREAD

**Issue by DustinSigwardNete** [NETESOLUTIONS/FOCUS-Maintenance#5]

**Comment by gregmarlownete** [comment]
please verify numbers

**Comment by DustinSigwardNete** [comment]
None of the values I checked added up to the Budgeted Labor column in the "Updated Contract Labor Values" spreadsheet.  Use the view below to validate the totals are correct

![image](https://cloud.githubusercontent.com/assets/10310724/12721336/528f114e-c8cd-11e5-88f3-6efe568ac362.png)
